<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <!--Author-->
        <PackageId>mdimai666.Mars.TelegramPlugin</PackageId>
        <!--Public-->
        <Authors>mdimai666</Authors>
        <Company>mdimai666</Company>
        <Product>Mars.TelegramPlugin</Product>
        <Title>Mars.TelegramPlugin</Title>
        <PackageTags>Mars;telegram</PackageTags>
        <Description>
            Mars.TelegramPlugin - provide telegram functions for Mars
            - Send notify
            - Add Nodes
        </Description>
        <PackageIcon>icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/mdimai666/Mars.TelegramPlugin</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyMetadata Include="PackageTags" Value="$(PackageTags)" />
        <AssemblyMetadata Include="PackageId" Value="$(PackageId)" />
        <AssemblyMetadata Include="RepositoryUrl" Value="$(RepositoryUrl)" />
        <AssemblyMetadata Include="PackageIcon" Value="$(PackageIcon)" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\assets\icon.png" Pack="true" PackagePath="\" Link="wwwroot\icon.png" CopyToOutputDirectory="PreserveNewest" />
        <PackageReference Include="mdimai666.Mars.Plugin.Sdk" Version="0.8.3-alpha.13">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.*" PrivateAssets="all" />
        <PackageReference Include="mdimai666.Mars.Plugin.Kit.Host" Version="0.8.3-alpha.13" />
        <PackageReference Include="Telegram.Bot" Version="22.10.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mars.TelegramPlugin.Nodes\Mars.TelegramPlugin.Nodes.csproj" />
        <ProjectReference Include="..\Mars.TelegramPlugin.Shared\Mars.TelegramPlugin.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.local.json">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
